#!/bin/sh

rm /etc/config/wireguard
touch /etc/config/wireguard

uci set wireguard.wireguard=wireguard

uci set wireguard.wireguard.enabled=$(jsonfilter -i /lib/gluon/site.json  -e "$.mesh_vpn.wireguard.enabled")
uci set wireguard.wireguard.iface=$(jsonfilter -i /lib/gluon/site.json  -e "$.mesh_vpn.wireguard.iface")
uci set wireguard.wireguard.iprange=$(jsonfilter -i /lib/gluon/site.json  -e "$.mesh_vpn.wireguard.iprange")
uci set wireguard.wireguard.privatekey=$(wg genkey)
uci set wireguard.wireguard.limit=$(jsonfilter -i /lib/gluon/site.json  -e "$.mesh_vpn.wireguard.limit")
uci set wireguard.wireguard.gretapip=$(jsonfilter -i /lib/gluon/site.json  -e "$.mesh_vpn.wireguard.gretapip")

#Wieviele peers haben wir denn?
anzahl=$(jsonfilter -i /lib/gluon/site.json  -e "$.mesh_vpn.wireguard.peers.*" | wc -l)
anzahl=`expr $anzahl - 1`

i=0
while [ $i -le $anzahl ]
do
	uci set wireguard.peer_$(expr $i + 1)=peer
	uci set wireguard.peer_$(expr $i + 1).endpoint=$(jsonfilter -i /lib/gluon/site.json  -e "$.mesh_vpn.wireguard.peers[$i].endpoint")
	uci set wireguard.peer_$(expr $i + 1).publickey=$(jsonfilter -i /lib/gluon/site.json  -e "$.mesh_vpn.wireguard.peers[$i].publickey")
	i=`expr $i + 1`
done



        



uci commit wireguard
